antibiotics = [
	'Cefoxitin',
	'Capreomycin',
	'Capreomycin',
	'Cefoxitin',
	'Rifamycin SV',
	'Cefoxitin',
	'Cloxacillin',
	'Rifamycin SV',
	'Neomycin',
	'Colistin',
	'Capreomycin',
	'Fosfomycin',
	'Metronidazole',
	'Cefsulodin',
	'Nigericin',
	'Capreomycin',
	'Metronidazole',
	'Capreomycin',
	'Doxycycline hyclate',
	'Cefsulodin',
	'Hygromycin ',
	'Nigericin',
	'Bleomycin',
	'Rifamycin SV',
	'Bleomycin',
	'Lomefloxacin',
	'Rifamycin SV',
	'Cloxacillin',
	'Radicicol',
	'Capreomycin',
	'Rifamycin SV',
	'Rifamycin SV',
	'Cloxacillin',
	'Nigericin',
	'Rifamycin SV',
	'Metronidazole',
	'Hygromycin ',
	'Cloxacillin',
	'Rifamycin SV',
	'Cloxacillin',
	'Rifamycin SV',
	'Rifamycin SV',
	'Lomefloxacin',
	'Cloxacillin',
	'Cloxacillin',
	'Hygromycin ',
	'Metronidazole',
	'Cefoxitin',
	'Cefsulodin',
	'Mecillinam',
	'CHIR090',
	'Rifamycin SV',
	'Cloxacillin',
	'Doxycycline',
	'Metronidazole',
	'Fosfomycin',
	'Doxycycline',
	'Mitomycin C',
	'Mecillinam',
	'Cloxacillin',
	'Metronidazole',
	'Mitomycin C',
	'Doxycycline hyclate',
	'Minocycline',
	'Rifamycin SV',
	'Rifamycin SV',
	'Bleomycin',
	'Cloxacillin',
	'Cloxacillin',
	'Rifamycin SV',
	'Metronidazole',
	'Bleomycin',
	'Fosfomycin',
	'Streptonigrin',
	'Metronidazole',
	'Rifamycin SV',
	'Cefoxitin',
	'Streptonigrin',
	'Minocycline',
	'Cefamandole',
	'Lomefloxacin',
	'Metronidazole',
	'CHIR090',
	'Doxycycline',
	'Colistin',
	'Cefoxitin',
	'Cefoxitin',
	'Clarythromycin',
	'Colistin',
	'Polymyxin B',
	'Streptonigrin',
	'Colistin',
	'Colistin']

antibiotics_dict = {}

for antibiotic in antibiotics:
	if antibiotic in antibiotics_dict:
		antibiotics_dict[antibiotic] += 1
	else:
		antibiotics_dict[antibiotic] = 1

antibiotics_dict = {k: v for k, v in sorted(antibiotics_dict.items(), reverse=True, key=lambda item: item[1])}

print(antibiotics_dict)

